### ISSUE TITLE
Redirect mutates the querystring

### ISSUE THREAD

**Issue by samsonradu** [ecphp/cas-lib#5]
## Steps required to reproduce the problem

Call an endpoint with a ticket parameter and a querystring parameter containing a dot (.)
`GET /simple?functionGroupMemberships.tag=AGENTS&lov=1&ticket=PT-.....`

## Expected Result
`302 /staff/simple?functionGroupMemberships.tag=AGENTS&lov=1`

## Actual Result
`302 /staff/simple?functionGroupMemberships_tag=AGENTS&lov=1`

**Comment by samsonradu** [comment]
https://github.com/symfony/symfony/issues/9009

**Comment by drupol** [comment]
> [symfony/symfony#9009](https://github.com/symfony/symfony/issues/9009)

The issue doesn't come from Symfony but from the parse_str() function.

**Comment by drupol** [comment]
I just tagged version 1.0.3 that contains this fix. Please update your project with composer update in a few minutes and let me know how it goes.

**Comment by drupol** [comment]
Update

I've been working on this since 3 days, trying to find a solution to avoid this critical issue when using API Platform and CAS Authentication.

In order to avoid the issue, I'm thinking about a better Symfony request converter that would avoid altering the query parameters.

Once this will be done, we will use it by default in ecphp/cas-bundle, but I need to make a proof of concept and some tests first.
